[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/nginx/Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
